// Auto-generated entity names from the scene


/**
 * Object containing all entity names in the scene for autocomplete support.
 */
export enum EntityNames {
  Admin_Tools = "Admin Tools",
  Armchair_D = "Armchair D",
  Armchair_D_2 = "Armchair D_2",
  Armchair_D_3 = "Armchair D_3",
  Billboard_Text = "Billboard_Text",
  Coffee_Table = "Coffee Table",
  Coffee_Table_2 = "Coffee Table_2",
  Concrete_Square_Planter = "Concrete Square Planter",
  Concrete_Square_Planter_2 = "Concrete Square Planter_2",
  Concrete_Square_Planter_2_3 = "Concrete Square Planter_2_3",
  Concrete_Square_Planter_3 = "Concrete Square Planter_3",
  Construction_Light = "Construction Light",
  Construction_Light_2 = "Construction Light_2",
  Construction_Metal_Fence = "Construction Metal Fence",
  Flower_crop = "Flower crop",
  Flower_crop_2 = "Flower crop_2",
  Hub = "Hub",
  Image = "Image",
  Image_2 = "Image_2",
  Macetas = "Macetas",
  Macetas_2 = "Macetas_2",
  New_Building = "New_Building",
  Palm_glb = "Palm.glb",
  Palm_glb_2 = "Palm.glb_2",
  Palm_glb_2_3 = "Palm.glb_2_3",
  Palm_glb_2_3_4 = "Palm.glb_2_3_4",
  Palm_glb_2_3_4_5 = "Palm.glb_2_3_4_5",
  Palms = "Palms",
  Placeholder = "Placeholder",
  Plane = "Plane",
  Plant_2 = "Plant 2",
  Plant_2_2 = "Plant 2_2",
  Plant_2_2_3 = "Plant 2_2_3",
  Plant_2_2_3_4 = "Plant 2_2_3_4",
  Plant_2_2_4 = "Plant 2_2_4",
  Plant_2_3 = "Plant 2_3",
  Planted_Fern = "Planted Fern",
  Planted_Fern_2 = "Planted Fern_2",
  Planted_Fern_2_3 = "Planted Fern_2_3",
  Planted_Fern_2_3_4 = "Planted Fern_2_3_4",
  Planted_Fern_2_3_4_5 = "Planted Fern_2_3_4_5",
  Planted_Fern_2_3_5 = "Planted Fern_2_3_5",
  Planted_Fern_2_4 = "Planted Fern_2_4",
  Planted_Fern_3 = "Planted Fern_3",
  Screen___NFTs = "Screen & NFTs",
  Spaceship_Chair = "Spaceship Chair",
  Spaceship_Chair_2 = "Spaceship Chair_2",
  Stairway_ETC = "Stairway_ETC",
  Streamers = "Streamers",
  Trigger_Area = "Trigger Area",
  Trigger_Area_2 = "Trigger Area_2",
  Video_Screen = "Video Screen",
  building_gltf = "building.gltf",
  door_01_gltf = "door_01.gltf",
  door_01_gltf_2 = "door_01.gltf_2",
} 
